# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Michael Dorman
tagline:             'Personal Website'
description:         'Michael Dorman'
url:                 https://michaeldorman.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Michael Dorman
  url:               
  email:             michael.dorman@mail.huji.ac.il

# Custom vars
version:             0.1.0

